package sandbox

import (
	"bytes"
	"context"
	"encoding/base64"
	"fmt"
	"os"
	"os/exec"
	"strings"
	"time"
)

// SSHEnvironment runs tools on a remote host via ansible's ssh
// connection plugin. The host pattern (`ansible_host`) is taken
// from the constructor; credentials come from the user's standard
// ssh-agent / ~/.ssh/config / sshpass flow — pilot does NOT manage
// them itself.
//
// Why not write a native ssh client?
//
//   - ansible already handles bastion/jump-host/ProxyCommand chains,
//     ssh-agent forwarding, known_hosts, host key verification,
//     and `become: true` (sudo) — all battle-tested.
//   - Pilot's job is "make ansible easier to drive", not "replace
//     the entire SSH stack".
//   - Keeping SSH out of pilot's process means: no key material in
//     memory, no agent socket juggling, no sshpass dependency.
//
// The "remote" Exec / ReadFile / WriteFile paths all shell out to
// `ansible <host> -m <module>`; ansible-playbook itself uses the
// ssh plugin naturally when the inventory's ansible_connection=ssh.
type SSHEnvironment struct {
	// Host is the inventory hostname or pattern this env targets.
	// Examples: "bastion-01", "web-*", "all".
	Host string
	// Inventory is the path to an ansible inventory file.
	Inventory string
	// User is the SSH user (default: ansible.cfg / inventory).
	User string
	// Port is the SSH port (default: 22).
	Port int
	// Become escalates via sudo for tasks that need root.
	Become bool
	// Binary overrides `ansible-playbook` / `ansible` (default: PATH lookup).
	Binary string
}

// NewSSHEnvironment returns an SSHEnvironment with the standard
// `ansible` and `ansible-playbook` binaries on PATH.
func NewSSHEnvironment(host, inventory string) *SSHEnvironment {
	return &SSHEnvironment{Host: host, Inventory: inventory}
}

// Start is a no-op (SSH sessions are stateless in this design —
// each command opens a fresh ssh connection via ansible).
func (e *SSHEnvironment) Start(_ context.Context) error { return nil }

// Stop is a no-op for the same reason.
func (e *SSHEnvironment) Stop(_ context.Context) error { return nil }

// Name returns "ssh".
func (e *SSHEnvironment) Name() string { return "ssh" }

// IsAvailable checks that the inventory exists; the SSH daemon itself
// is reachable-or-not only when we run a command, so we don't probe
// it eagerly.
func (e *SSHEnvironment) IsAvailable(_ context.Context) error {
	if e.Host == "" {
		return fmt.Errorf("ssh: host is required")
	}
	if e.Inventory == "" {
		return fmt.Errorf("ssh: inventory is required")
	}
	return nil
}

// ConnectionInfo returns the ssh connection fragment that should be
// merged into the per-run inventory generated by pilot.
func (e *SSHEnvironment) ConnectionInfo() AnsibleConnection {
	c := AnsibleConnection{
		Host:           e.Host,
		ConnectionType: "ssh",
	}
	if e.User != "" {
		c.User = e.User
	}
	if e.Port > 0 {
		c.Port = e.Port
	}
	return c
}

// Exec implements the Environment interface. argv is interpreted as a
// command line; the first element is the program and the rest are
// positional arguments. We DO NOT route argv through a shell — this
// matches LocalEnvironment's contract. For shell-needing calls, use
// RunCommand with module=shell.
//
// Implementation: if the binary is a path on the local host (e.g.
// `/usr/bin/uptime`), we can't trivially exec it on the remote. We
// fall back to `ansible <host> -m command -a "<full argv joined>"`.
// This is best-effort: if a tool relies on local-only binaries, the
// SSH env will reject it via the executor's path allow-list.
func (e *SSHEnvironment) Exec(ctx context.Context, argv []string, opts ExecOptions) (*ExecResult, error) {
	if len(argv) == 0 {
		return nil, fmt.Errorf("sandbox: empty argv")
	}
	if err := e.IsAvailable(ctx); err != nil {
		return nil, err
	}

	timeout := opts.Timeout
	if timeout <= 0 {
		timeout = 30 * time.Second
	}
	c, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()

	// Join argv into one shell-safe string. This is the standard
	// ansible pattern; tools that need fine-grained control should
	// call RunCommand with module=command instead.
	cmdline := strings.Join(argv, " ")
	out, err := e.runAnsibleAdHoc(c, "command", cmdline)
	res := &ExecResult{Stdout: out, Cmd: "ansible " + e.Host + " -m command -a " + cmdline}
	if err != nil {
		if ctx.Err() == context.DeadlineExceeded {
			res.ExitCode = -1
			return res, fmt.Errorf("sandbox.SSHEnvironment.Exec: timeout after %s", timeout)
		}
		res.ExitCode = 1
		return res, err
	}
	res.ExitCode = 0
	return res, nil
}

// ReadFile reads path via `ansible -m slurp` and base64-decodes
// the result. We use slurp instead of `cat` because slurp returns
// the file in one shot regardless of size and gives a clean exit
// code (so partial reads raise an error rather than a truncated
// result).
func (e *SSHEnvironment) ReadFile(ctx context.Context, path string) ([]byte, error) {
	if err := e.IsAvailable(ctx); err != nil {
		return nil, err
	}
	out, err := e.runAnsibleAdHoc(ctx, "slurp", "src="+path)
	if err != nil {
		return nil, fmt.Errorf("ssh: slurp %s: %w", path, err)
	}
	// ansible -m slurp output (with --one-line) looks like:
	//   host | SUCCESS => {"changed":false,"content":"BASE64..."}
	idx := strings.Index(out, "\"content\":")
	if idx < 0 {
		return nil, fmt.Errorf("ssh: slurp %s: no content in output: %s", path, out)
	}
	rest := out[idx+len("\"content\":"):]
	q1 := strings.Index(rest, `"`)
	if q1 < 0 {
		return nil, fmt.Errorf("ssh: slurp %s: malformed output: %s", path, out)
	}
	body := rest[q1+1:]
	q2 := strings.Index(body, `"`)
	if q2 < 0 {
		return nil, fmt.Errorf("ssh: slurp %s: malformed output: %s", path, out)
	}
	raw, err := base64.StdEncoding.DecodeString(body[:q2])
	if err != nil {
		return nil, fmt.Errorf("ssh: slurp %s: base64 decode: %w", path, err)
	}
	return raw, nil
}

// WriteFile writes data to path with the given mode by piping a
// base64-encoded payload through `ansible -m shell`. For tiny
// config files this is fine; for large files the caller should
// drop to SCP (out of scope here).
func (e *SSHEnvironment) WriteFile(ctx context.Context, path string, data []byte, mode os.FileMode) error {
	if err := e.IsAvailable(ctx); err != nil {
		return err
	}
	encoded := base64.StdEncoding.EncodeToString(data)
	script := fmt.Sprintf(
		"echo %s | base64 -d > %s && chmod %o %s",
		encoded, path, mode, path,
	)
	_, err := e.runAnsibleAdHoc(ctx, "shell", script)
	return err
}

// runAnsibleAdHoc shells out to `ansible <host> -i <inv> -m <module>`.
// It is the common path for Exec / ReadFile / WriteFile.
func (e *SSHEnvironment) runAnsibleAdHoc(ctx context.Context, module, args string) (string, error) {
	bin := e.Binary
	if bin == "" {
		bin = "ansible"
	}
	argv := []string{e.Host, "-i", e.Inventory, "-m", module, "-a", args}
	if e.User != "" {
		argv = append(argv, "--user", e.User)
	}
	if e.Port > 0 {
		argv = append(argv, "--port", fmt.Sprintf("%d", e.Port))
	}
	if e.Become {
		argv = append(argv, "--become")
	}
	cmd := exec.CommandContext(ctx, bin, argv...)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		return strings.TrimSpace(stdout.String() + "\n" + stderr.String()), err
	}
	return strings.TrimSpace(stdout.String()), nil
}

// Compile-time check that SSHEnvironment satisfies Environment.
var _ Environment = (*SSHEnvironment)(nil)

// Suppress unused-import warnings on bytes when the slice isn't
// referenced by tests directly.
var _ = bytes.NewBuffer
