package tools

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/anomalyco/pilot/internal/docs"
	"github.com/anomalyco/pilot/internal/ollama"
	"gopkg.in/yaml.v3"
)

// GenerateRollbackTool asks the LLM to produce a rollback playbook for
// a previously-applied proposal. The generated YAML is written to
// $DataDir/generated-rollbacks/<proposal-id>-<timestamp>.yml for
// human review before the user runs it (via run_ansible).
type GenerateRollbackTool struct {
	Ollama       *ollama.Client
	GeneratedDir string
	SystemPrompt string
	ModuleIndex  *docs.ModuleIndex
}

func (t *GenerateRollbackTool) Spec() *Spec {
	return &Spec{
		Name: "generate_rollback",
		Description: "Generate a rollback Ansible playbook for a previously-applied proposal. The output is written to disk as a YAML file for human review. The rollback is NOT applied automatically — the user must run it explicitly via run_ansible after inspecting the generated tasks.",
		RiskLevel:    "low", // write a file, not apply
		Reversible:   true,
		DryRunSafe:   true,
		Parameters:   generateRollbackArgs,
	}
}

type generateRollbackArgsStruct struct {
	ProposalID  string `json:"proposal_id"`
	Description string `json:"description"`
	// The proposal's applied state, when available. Used by the
	// LLM to infer what to undo.
	OriginalTool string `json:"original_tool"`
	OriginalArgs string `json:"original_args"`
	// Context: the rationale or result content of the original
	// proposal.
	Context string `json:"context"`
}

func (t *GenerateRollbackTool) Execute(ctx context.Context, args json.RawMessage) (*Result, error) {
	var a generateRollbackArgsStruct
	if err := json.Unmarshal(args, &a); err != nil {
		return nil, fmt.Errorf("generate_rollback: invalid args: %w", err)
	}
	if a.ProposalID == "" {
		return nil, fmt.Errorf("generate_rollback: proposal_id is required")
	}
	if t.Ollama == nil {
		return &Result{Content: "ERROR: ollama client not configured", IsError: true}, nil
	}

	prompt := buildRollbackPrompt(a)
	resp, err := t.Ollama.Chat(ctx,
		[]ollama.Message{
			{Role: "system", Content: t.SystemPrompt},
			{Role: "user", Content: prompt},
		},
		nil,
	)
	if err != nil {
		return &Result{Content: fmt.Sprintf("ERROR: ollama call failed: %v", err), IsError: true}, nil
	}

	yamlText := extractYAML(resp.Message.Content)
	if yamlText == "" {
		return &Result{Content: fmt.Sprintf("ERROR: model did not return a YAML code block.\n\nRaw response:\n%s", resp.Message.Content), IsError: true}, nil
	}

	// Validate YAML syntax
	var temp any
	if err := yaml.Unmarshal([]byte(yamlText), &temp); err != nil {
		return &Result{Content: fmt.Sprintf("ERROR: generated content is not valid YAML: %v\n\nYAML:\n%s", err, yamlText), IsError: true}, nil
	}

	trimmed := strings.TrimSpace(yamlText)
	if !strings.HasPrefix(trimmed, "- name:") && !strings.HasPrefix(trimmed, "---") {
		return &Result{Content: fmt.Sprintf("ERROR: generated content does not look like an Ansible task.\n\nYAML:\n%s", yamlText), IsError: true}, nil
	}

	dir := t.GeneratedDir
	if dir == "" {
		dir = filepath.Join(os.TempDir(), "pilot", "rollback")
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return &Result{Content: fmt.Sprintf("ERROR: mkdir: %v", err), IsError: true}, nil
	}
	ts := time.Now().Format("20060102-150405")
	path := filepath.Join(dir, fmt.Sprintf("%s-%s.yml", a.ProposalID, ts))
	header := fmt.Sprintf("# Rollback for proposal %s\n# Generated by pilot at %s\n# DO NOT auto-apply — review before running with run_ansible.\n\n",
		a.ProposalID, time.Now().Format(time.RFC3339))
	if err := os.WriteFile(path, []byte(header+yamlText), 0o644); err != nil {
		return &Result{Content: fmt.Sprintf("ERROR: write file: %v", err), IsError: true}, nil
	}

	var sb strings.Builder
	fmt.Fprintf(&sb, "Rollback playbook written to: %s\n\n", path)
	fmt.Fprintf(&sb, "--- generated YAML ---\n%s\n", yamlText)
	fmt.Fprintf(&sb, "\n--- next step ---\n")
	fmt.Fprintf(&sb, "Run with run_ansible --check=true to preview the rollback, then run_ansible --check=false to apply it.\n")
	meta, _ := json.Marshal(map[string]string{"rollback_path": path})
	return &Result{
		Content:  sb.String(),
		Metadata: meta,
	}, nil
}

func buildRollbackPrompt(a generateRollbackArgsStruct) string {
	var sb strings.Builder
	sb.WriteString("Generate an Ansible ROLLBACK playbook (tasks that UNDO the original change) for the following proposal.\n\n")
	if a.Description != "" {
		fmt.Fprintf(&sb, "Description of the original change: %s\n", a.Description)
	}
	if a.OriginalTool != "" {
		fmt.Fprintf(&sb, "Original tool that was applied: %s\n", a.OriginalTool)
	}
	if a.OriginalArgs != "" {
		fmt.Fprintf(&sb, "Original arguments: %s\n", a.OriginalArgs)
	}
	if a.Context != "" {
		fmt.Fprintf(&sb, "Context: %s\n", a.Context)
	}
	sb.WriteString(`
Requirements:
- Output ONLY a single YAML code block. No prose, no commentary.
- The rollback MUST restore the system to a state equivalent to (or
  safer than) before the original change.
- Use idempotent modules (lineinfile with state=absent, file with
  state=absent, service with state=stopped/started, etc.).
- Include 'become: true' on tasks that need root.
- If the rollback is risky (e.g. deleting files), prefer a comment
  noting the risk rather than executing it.
- If you cannot reliably undo the change (e.g. the original tool
  generated a random secret), output a single task that prints a
  warning to the operator.

Example output format:
` + "```yaml" + `
- name: Rollback CIS 5.2.1 (re-enable PermitRootLogin)
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin yes'
    state: present
  become: true
` + "```" + `

Now generate the rollback:
`)
	return sb.String()
}

var generateRollbackArgs = json.RawMessage(`{
  "type": "object",
  "properties": {
    "proposal_id": {
      "type": "string",
      "description": "The proposal ID this rollback is for. Used for the output filename and as a comment in the YAML."
    },
    "description": {
      "type": "string",
      "description": "What the original proposal did (the rationale)."
    },
    "original_tool": {
      "type": "string",
      "description": "The tool name from the original proposal (e.g. 'run_ansible', 'generate_playbook')."
    },
    "original_args": {
      "type": "string",
      "description": "The original args (as JSON), to give the LLM context about what to undo."
    },
    "context": {
      "type": "string",
      "description": "Any additional context (e.g. the result content from the original proposal)."
    }
  },
  "required": ["proposal_id"]
}`)
