package tools

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/anomalyco/pilot/internal/docs"
	"github.com/anomalyco/pilot/internal/ollama"
	"gopkg.in/yaml.v3"
)

// GeneratePlaybookTool asks the LLM to generate an Ansible task YAML
// from a description. The generated YAML is written to a file in
// GeneratedDir for human review before apply.
//
// When ModuleIndex is non-nil, the tool retrieves the top relevant
// ansible-doc chunks via the LLM-friendly retriever and inlines them
// into the prompt. This drastically reduces hallucinated module names,
// parameter names, and enum values.
type GeneratePlaybookTool struct {
	Ollama       *ollama.Client
	GeneratedDir string
	SystemPrompt string
	ModuleIndex  *docs.ModuleIndex
	// MaxRAGHits caps the number of chunks included in the prompt.
	// Zero means default (3).
	MaxRAGHits int
}

func (t *GeneratePlaybookTool) Spec() *Spec {
	return &Spec{
		Name:        "generate_playbook",
		Description: "Generate a single Ansible task (or short playbook) from a natural-language description. The output is written as a YAML file in the generated-playbooks directory. The task is returned as a code block for the proposal diff. NEVER apply automatically — the user must approve the apply step.",
		RiskLevel:   "low",
		Reversible:  true,
		// generate_playbook WRITES a file, so it's not safe under --dry-run-all
		// by default. The agent loop intercepts and produces a "would generate"
		// preview instead of calling the executor.
		DryRunSafe: false,
		Parameters: generateTaskArgs,
	}
}

type generateTaskArgsStruct struct {
	Description string `json:"description"`
	CISControl  string `json:"cis_control"`
	TargetFile  string `json:"target_file"`
}

func (t *GeneratePlaybookTool) Execute(ctx context.Context, args json.RawMessage) (*Result, error) {
	var a generateTaskArgsStruct
	if err := json.Unmarshal(args, &a); err != nil {
		return nil, fmt.Errorf("generate_playbook: invalid args: %w", err)
	}
	if a.Description == "" {
		return nil, fmt.Errorf("generate_playbook: description is required")
	}
	if t.Ollama == nil {
		return &Result{Content: "ERROR: ollama client not configured", IsError: true}, nil
	}

	// Build a focused prompt asking for valid Ansible YAML only.
	// When a module index is available we inline the top RAG hits
	// so the LLM uses the exact module / parameter names from the
	// installed ansible-core (not its training-data memory).
	prompt := t.buildGenerationPrompt(ctx, a)

	resp, err := t.Ollama.Chat(ctx,
		[]ollama.Message{
			{Role: "system", Content: t.SystemPrompt},
			{Role: "user", Content: prompt},
		},
		nil, // no tools — we want pure YAML output
	)
	if err != nil {
		return &Result{Content: fmt.Sprintf("ERROR: ollama call failed: %v", err), IsError: true}, nil
	}

	yamlText := extractYAML(resp.Message.Content)
	if yamlText == "" {
		return &Result{Content: fmt.Sprintf("ERROR: model did not return a YAML code block.\n\nRaw response:\n%s", resp.Message.Content), IsError: true}, nil
	}

	// Validate YAML syntax
	var temp any
	if err := yaml.Unmarshal([]byte(yamlText), &temp); err != nil {
		return &Result{Content: fmt.Sprintf("ERROR: generated content is not valid YAML: %v\n\nYAML:\n%s", err, yamlText), IsError: true}, nil
	}

	// Sanity-check the YAML by ensuring it starts with `- name:` or `---`
	trimmed := strings.TrimSpace(yamlText)
	if !strings.HasPrefix(trimmed, "- name:") && !strings.HasPrefix(trimmed, "---") {
		return &Result{Content: fmt.Sprintf("ERROR: generated content does not look like a valid Ansible task.\n\nYAML:\n%s", yamlText), IsError: true}, nil
	}

	// Persist to disk
	if t.GeneratedDir == "" {
		t.GeneratedDir = filepath.Join(os.TempDir(), "pilot", "generated")
	}
	if err := os.MkdirAll(t.GeneratedDir, 0o755); err != nil {
		return &Result{Content: fmt.Sprintf("ERROR: mkdir: %v", err), IsError: true}, nil
	}
	ts := time.Now().Format("20060102-150405")
	safe := sanitizeFilename(a.Description)
	if len(safe) > 40 {
		safe = safe[:40]
	}
	path := filepath.Join(t.GeneratedDir, fmt.Sprintf("%s-%s.yml", ts, safe))
	header := fmt.Sprintf("# Generated by pilot at %s\n# Description: %s\n# CIS: %s\n\n",
		time.Now().Format(time.RFC3339), a.Description, a.CISControl)
	if err := os.WriteFile(path, []byte(header+yamlText), 0o644); err != nil {
		return &Result{Content: fmt.Sprintf("ERROR: write file: %v", err), IsError: true}, nil
	}

	var sb strings.Builder
	fmt.Fprintf(&sb, "Generated playbook written to: %s\n\n", path)
	fmt.Fprintf(&sb, "--- generated YAML ---\n%s\n", yamlText)
	fmt.Fprintf(&sb, "\n--- next step ---\n")
	fmt.Fprintf(&sb, "Use run_ansible with check=true to preview changes, then propose apply.\n")
	return &Result{Content: sb.String()}, nil
}

// buildGenerationPrompt builds the prompt, optionally inlining top RAG
// hits from the module index. The inline RAG block makes the LLM use
// the exact module / parameter / enum names from the installed
// ansible-core instead of relying on training memory.
func (t *GeneratePlaybookTool) buildGenerationPrompt(ctx context.Context, a generateTaskArgsStruct) string {
	var sb strings.Builder
	sb.WriteString("Generate ONE Ansible task (or a tiny playbook) that accomplishes the following.\n\n")
	fmt.Fprintf(&sb, "Description: %s\n", a.Description)
	if a.CISControl != "" {
		fmt.Fprintf(&sb, "CIS control: %s\n", a.CISControl)
	}
	if a.TargetFile != "" {
		fmt.Fprintf(&sb, "Target file on host: %s\n", a.TargetFile)
	}
	if ragCtx := t.ragContext(ctx, a.Description); ragCtx != "" {
		sb.WriteString("\n=== Relevant Ansible module documentation (from local index) ===\n")
		sb.WriteString(ragCtx)
		sb.WriteString("\n=== End of retrieved context ===\n\n")
	}
	sb.WriteString(`
Requirements:
- Output ONLY a single YAML code block. No prose, no commentary.
- Use the EXACT module name (FQCN) and parameter names from the retrieved context above. Do not invent.
- Use the EXACT enum values listed in the retrieved choices (e.g. if 'choices' lists [started, stopped, restarted, reloaded], do not use 'restart' alone).
- Use idempotent modules (lineinfile, copy with validate, ansible.posix.sysctl, etc.).
- For tasks modifying files (like lineinfile, copy, template, replace, blockinfile), ALWAYS set 'backup: yes' to ensure a backup is kept.
- Include 'become: true' on tasks that need root.
- Use fully-qualified collection names (ansible.builtin.lineinfile, ansible.posix.sysctl) when possible.
- The task must be safe to run with --check --diff.
- If the change is a line edit, use lineinfile with regexp + line.
- Do NOT use raw shell unless absolutely necessary.

Example output format:
` + "```yaml" + `
- name: Disable root SSH login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
  become: true
` + "```" + `

Now generate the task:
`)
	return sb.String()
}

// ragContext queries the module index for the most relevant chunks
// and renders them as a compact inline block. Returns "" when the
// index is unavailable or empty (so the caller can elide the section).
func (t *GeneratePlaybookTool) ragContext(ctx context.Context, description string) string {
	if t.ModuleIndex == nil || t.ModuleIndex.Size() == 0 {
		return ""
	}
	limit := t.MaxRAGHits
	if limit <= 0 {
		limit = 3
	}
	matches, err := t.ModuleIndex.SearchLLM(description, docs.SearchLLMOpts{
		Limit:          limit,
		PreferParam:    true,
		PrefixMatchRef: true,
	})
	if err != nil || len(matches) == 0 {
		return ""
	}
	var sb strings.Builder
	for i, m := range matches {
		c := t.ModuleIndex.ChunkByIndex(m.Index)
		// Strip the [search-text] tail that the chunker appends; we
		// only want the human-facing body in the prompt.
		body := c.Text
		if j := strings.Index(body, "\n\n[search-text]"); j >= 0 {
			body = body[:j]
		}
		body = strings.TrimSpace(body)
		if body == "" {
			continue
		}
		// Cap each entry to ~1200 chars to keep total prompt size sane.
		if len(body) > 1200 {
			body = body[:1200] + "..."
		}
		fmt.Fprintf(&sb, "[%d] %s :: %s\n%s\n\n", i+1, c.Ref, c.Section, body)
	}
	return sb.String()
}

func extractYAML(s string) string {
	// Look for ```yaml ... ``` or ``` ... ```
	if idx := strings.Index(s, "```yaml"); idx >= 0 {
		end := strings.Index(s[idx+7:], "```")
		if end >= 0 {
			return strings.TrimSpace(s[idx+7 : idx+7+end])
		}
	}
	if idx := strings.Index(s, "```"); idx >= 0 {
		end := strings.Index(s[idx+3:], "```")
		if end >= 0 {
			body := strings.TrimSpace(s[idx+3 : idx+3+end])
			// only accept if it looks like YAML
			if strings.HasPrefix(body, "- ") || strings.HasPrefix(body, "---") {
				return body
			}
		}
	}
	return ""
}

func sanitizeFilename(s string) string {
	out := strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '-' || r == '_' {
			return r
		}
		return '-'
	}, strings.ToLower(s))
	return out
}
