#File modified by ipa-client-install

[global]
basedn = dc=ipa,dc=pilot,dc=internal
realm = IPA.PILOT.INTERNAL
domain = ipa.pilot.internal
server = ipa2.ipa.pilot.internal
host = ipa-ha-client.ipa.pilot.internal
xmlrpc_uri = https://ipa2.ipa.pilot.internal/ipa/xml
enable_ra = True


