#File modified by ipa-client-install

includedir /etc/krb5.conf.d/
[libdefaults]
  default_realm = IPA.PILOT.INTERNAL
  dns_lookup_realm = false
  rdns = false
  dns_canonicalize_hostname = false
  dns_lookup_kdc = true
  ticket_lifetime = 24h
  forwardable = true
  udp_preference_limit = 0
  default_ccache_name = KEYRING:persistent:%{uid}


[realms]
  IPA.PILOT.INTERNAL = {
    kdc = ipa2.ipa.pilot.internal:88
    master_kdc = ipa2.ipa.pilot.internal:88
    admin_server = ipa2.ipa.pilot.internal:749
    kpasswd_server = ipa2.ipa.pilot.internal:464
    default_domain = ipa.pilot.internal
    pkinit_anchors = FILE:/var/lib/ipa-client/pki/kdc-ca-bundle.pem
    pkinit_pool = FILE:/var/lib/ipa-client/pki/ca-bundle.pem

  }


[domain_realm]
  .ipa.pilot.internal = IPA.PILOT.INTERNAL
  ipa.pilot.internal = IPA.PILOT.INTERNAL
  ipa-ha-client.ipa.pilot.internal = IPA.PILOT.INTERNAL


