package inventory

import (
	"fmt"
	"strings"
)

// hostVarsKind discriminates how a hostVarsKey's placeholder renders —
// added so a future list-shaped host_vars key (e.g. a per-host override
// list) doesn't need another catalog redesign; hostVarsKindScalar is the
// zero value, so every existing entry needs no change.
type hostVarsKind int

const (
	hostVarsKindScalar hostVarsKind = iota
	hostVarsKindList
)

// hostVarsKey describes one host_vars variable that has no safe cross-host
// default — Value/Values is always the empty placeholder (never a guessed
// real value), selected by Kind; Comment explains why it must be set per
// host.
type hostVarsKey struct {
	Name    string
	Kind    hostVarsKind
	Value   string   // placeholder when Kind == hostVarsKindScalar
	Values  []string // placeholder when Kind == hostVarsKindList
	Comment string
}

var hostVarsKeyCatalog = map[string]hostVarsKey{
	"prometheus_site_label": {
		Name:  "prometheus_site_label",
		Value: "",
		Comment: "這一站的站名,寫進 Prometheus external_labels.site,thanos-query 全局查詢\n" +
			"靠這個欄位分辨資料來自哪一站(見 docs/verification/prometheus.md §1.5)。\n" +
			"必填、沒有預設值——每一站都不同,沿用預設會讓忘記覆寫的第二站悄悄跟\n" +
			"第一站標籤撞名,破壞跨站 Thanos 資料聚合。",
	},
}

// hostVarsKeyOrder pins deterministic rendering order for keys that appear
// together, independent of the order roles happen to be listed in.
var hostVarsKeyOrder = []string{
	"prometheus_site_label",
}

// HostVarsKeysForRoles returns the deduped, ordered set of host_vars keys
// that should appear in the generated skeleton for the given roles.
func HostVarsKeysForRoles(roles []string) []string {
	contracts := roleContractsByName()
	seen := map[string]bool{}
	var out []string
	for _, role := range roles {
		for _, key := range contracts[role].HostVarsKeys {
			if !seen[key] {
				seen[key] = true
				out = append(out, key)
			}
		}
	}
	sortStringsByReference(out, hostVarsKeyOrder)
	return out
}

// ExpectedHostVarsKeysForRoles is an alias for HostVarsKeysForRoles, named
// to match ExpectedVaultKeysForRoles's test-facing convention.
func ExpectedHostVarsKeysForRoles(roles []string) []string {
	return HostVarsKeysForRoles(roles)
}

// GenerateHostVarsSkeleton renders a host_vars/<host>.yml skeleton containing
// only the keys implied by h's roles, as empty-string placeholders with an
// explanatory comment — it never invents a real value. ok=false means h's
// roles need no generated host_vars skeleton.
func GenerateHostVarsSkeleton(h Host) (rendered string, ok bool) {
	keys := HostVarsKeysForRoles(h.Roles)
	if len(keys) == 0 {
		return "", false
	}

	var sb strings.Builder
	sb.WriteString("# =============================================================================\n")
	sb.WriteString(fmt.Sprintf("#  host_vars/%s.yml skeleton — generated by `pilot inventory generate`\n", h.Name))
	sb.WriteString("# =============================================================================\n")
	sb.WriteString("#\n")
	sb.WriteString("# These vars have no safe default shared across hosts — each one must be set\n")
	sb.WriteString("# to a real, per-host value below before deploying for real.\n")
	sb.WriteString("# =============================================================================\n")
	sb.WriteString("---\n\n")

	for i, name := range keys {
		key := hostVarsKeyCatalog[name]
		if key.Comment != "" {
			for _, line := range strings.Split(key.Comment, "\n") {
				sb.WriteString(fmt.Sprintf("# %s\n", line))
			}
		}
		switch key.Kind {
		case hostVarsKindList:
			sb.WriteString(fmt.Sprintf("%s: [%s]\n", key.Name, strings.Join(key.Values, ", ")))
		default:
			sb.WriteString(fmt.Sprintf("%s: %q\n", key.Name, key.Value))
		}
		if i < len(keys)-1 {
			sb.WriteString("\n")
		}
	}

	return sb.String(), true
}
