package inventory

import (
	"reflect"
	"strings"
	"testing"
)

const sshRecordingSource = `
hosts:
  web-01:
    ansible_host: "10.10.0.21"
    roles: [freeipa-client, linux-servers]
  db-prod-01:
    ansible_host: "10.10.0.31"
    roles: [freeipa-client, linux-servers]
    ssh_recording: terminal_output
  no-record-01:
    ansible_host: "10.10.0.51"
    roles: [freeipa-client, linux-servers]
    ssh_recording: off
`

func parseSSHRecordingHosts(t *testing.T, src string) map[string]Host {
	t.Helper()
	hf, err := Parse([]byte(src))
	if err != nil {
		t.Fatal(err)
	}
	byName := map[string]Host{}
	for _, h := range hf.Hosts {
		byName[h.Name] = h
	}
	return byName
}

func TestParseSSHRecording_Omitted(t *testing.T) {
	h := parseSSHRecordingHosts(t, sshRecordingSource)["web-01"]
	if h.SSHRecording != "" {
		t.Fatalf("omitted ssh_recording = %q, want empty (inherit)", h.SSHRecording)
	}
}

func TestParseSSHRecording_Off(t *testing.T) {
	// yaml.v3 decodes a bare `off` as the string "off" (YAML 1.2 core
	// schema), not a boolean — this is what makes the unquoted form legal.
	h := parseSSHRecordingHosts(t, sshRecordingSource)["no-record-01"]
	if h.SSHRecording != SSHRecordingOff {
		t.Fatalf("ssh_recording = %q, want off", h.SSHRecording)
	}
}

func TestParseSSHRecording_TerminalOutput(t *testing.T) {
	h := parseSSHRecordingHosts(t, sshRecordingSource)["db-prod-01"]
	if h.SSHRecording != SSHRecordingTerminalOutput {
		t.Fatalf("ssh_recording = %q, want terminal_output", h.SSHRecording)
	}
}

func TestParse_SSHRecordingNotCopiedIntoExtra(t *testing.T) {
	for name, h := range parseSSHRecordingHosts(t, sshRecordingSource) {
		if _, ok := h.Extra["ssh_recording"]; ok {
			t.Errorf("host %s: ssh_recording leaked into Extra: %+v", name, h.Extra)
		}
	}
}

func TestParse_AnnotationSSHRecordingHasNoPolicyEffect(t *testing.T) {
	h := parseSSHRecordingHosts(t, `
hosts:
  web-01:
    ansible_host: "10.10.0.21"
    roles: [linux-servers]
    annotations:
      ssh_recording: terminal_output
`)["web-01"]
	if h.SSHRecording != "" {
		t.Fatalf("annotations.ssh_recording set the policy field to %q; annotations must stay descriptive-only", h.SSHRecording)
	}
	if h.Annotations["ssh_recording"] != "terminal_output" {
		t.Fatalf("annotation value lost: %+v", h.Annotations)
	}
}

func lintMessages(t *testing.T, src string) []string {
	t.Helper()
	hf, err := Parse([]byte(src))
	if err != nil {
		t.Fatalf("Parse must not fail on a bad ssh_recording value (Lint reports it): %v", err)
	}
	var out []string
	for _, i := range Lint(hf) {
		if i.Severity == "error" {
			out = append(out, i.String())
		}
	}
	return out
}

func requireLintError(t *testing.T, src, want string) {
	t.Helper()
	msgs := lintMessages(t, src)
	for _, m := range msgs {
		if strings.Contains(m, want) {
			return
		}
	}
	t.Fatalf("lint errors %q do not contain %q", msgs, want)
}

func TestLintSSHRecording_RejectsTerminalIOReserved(t *testing.T) {
	requireLintError(t, `
hosts:
  pci-admin-01:
    ansible_host: "10.0.0.41"
    roles: [linux-servers]
    ssh_recording: terminal_io
`, `ssh_recording "terminal_io" is reserved for a future release`)
}

func TestLintSSHRecording_RejectsBool(t *testing.T) {
	for _, v := range []string{"true", "false"} {
		requireLintError(t, `
hosts:
  db-01:
    ansible_host: "10.0.0.31"
    roles: [linux-servers]
    ssh_recording: `+v+`
`, `unknown ssh_recording "`+v+`" (must be off|terminal_output, or omitted; quote the value`)
	}
}

func TestLintSSHRecording_RejectsUnknown(t *testing.T) {
	for _, v := range []string{"output", "terminal", "all", "enabled", "disabled", "yes", "1"} {
		requireLintError(t, `
hosts:
  db-01:
    ansible_host: "10.0.0.31"
    roles: [linux-servers]
    ssh_recording: `+v+`
`, `unknown ssh_recording "`+v+`"`)
	}
}

func TestLintSSHRecording_AcceptsValidValues(t *testing.T) {
	if msgs := lintMessages(t, sshRecordingSource); len(msgs) != 0 {
		t.Fatalf("valid ssh_recording values produced lint errors: %q", msgs)
	}
}

func TestLint_GeneratedKeyCollisionInExtra(t *testing.T) {
	for _, k := range []string{"pilot_ssh_recording", "pilot_annotations"} {
		requireLintError(t, `
hosts:
  db-01:
    ansible_host: "10.0.0.31"
    roles: [linux-servers]
    `+k+`: terminal_output
`, `host var "`+k+`" is generated by pilot and must not be set directly`)
	}
}

func TestGenerate_SSHRecordingQuoted(t *testing.T) {
	hf, err := Parse([]byte(sshRecordingSource))
	if err != nil {
		t.Fatal(err)
	}
	out, err := Generate(hf)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"    db-prod-01:\n      ansible_host: \"10.10.0.31\"\n      pilot_ssh_recording: \"terminal_output\"\n",
		"    no-record-01:\n      ansible_host: \"10.10.0.51\"\n      pilot_ssh_recording: \"off\"\n",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("generated inventory missing %q:\n%s", want, out)
		}
	}
}

func TestGenerate_OmittedSSHRecordingNotRendered(t *testing.T) {
	hf, err := Parse([]byte(sshRecordingSource))
	if err != nil {
		t.Fatal(err)
	}
	out, err := Generate(hf)
	if err != nil {
		t.Fatal(err)
	}
	inWeb := false
	for _, line := range strings.Split(out, "\n") {
		if strings.HasPrefix(line, "    ") && !strings.HasPrefix(line, "     ") {
			inWeb = line == "    web-01:"
			continue
		}
		if inWeb && strings.Contains(line, "pilot_ssh_recording") {
			t.Fatalf("omitted ssh_recording rendered %q for web-01:\n%s", line, out)
		}
	}
}

func TestGenerate_RefusesInvalidSSHRecording(t *testing.T) {
	hf, err := Parse([]byte(`
hosts:
  db-01:
    ansible_host: "10.0.0.31"
    roles: [linux-servers]
    ssh_recording: false
`))
	if err != nil {
		t.Fatal(err)
	}
	if _, err := Generate(hf); err == nil || !strings.Contains(err.Error(), "unknown ssh_recording") {
		t.Fatalf("Generate err = %v, want refusal citing ssh_recording", err)
	}
}

func TestRender_SSHRecordingRoundTrip(t *testing.T) {
	hf, err := Parse([]byte(sshRecordingSource))
	if err != nil {
		t.Fatal(err)
	}
	rendered, err := Render(hf)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(rendered, "    ssh_recording: \"terminal_output\"\n") || !strings.Contains(rendered, "    ssh_recording: \"off\"\n") {
		t.Fatalf("rendered source missing ssh_recording lines:\n%s", rendered)
	}
	hf2, err := Parse([]byte(rendered))
	if err != nil {
		t.Fatalf("re-parse: %v\n%s", err, rendered)
	}
	if !reflect.DeepEqual(hf.Hosts, hf2.Hosts) {
		t.Fatalf("round-trip mismatch:\nbefore=%+v\nafter=%+v", hf.Hosts, hf2.Hosts)
	}
}
