package inventory

import "fmt"

// SSHRecording is a host's per-host SSH terminal recording policy
// (per-host recording spec §3/§5). The zero value means "inherit the
// gateway default", which is NOT the same as SSHRecordingOff: an explicit
// off overrides a non-metadata gateway default, an omitted field does not.
type SSHRecording string

const (
	// SSHRecordingOff explicitly disables terminal recording for the host.
	SSHRecordingOff SSHRecording = "off"
	// SSHRecordingTerminalOutput records the host's terminal output.
	SSHRecordingTerminalOutput SSHRecording = "terminal_output"
	// sshRecordingTerminalIOReserved is the gateway-level terminal_io mode.
	// It is deliberately not a valid host value yet (spec decision D-A):
	// typed input cannot be redacted reliably on the Gateway SSH relay.
	sshRecordingTerminalIOReserved SSHRecording = "terminal_io"
)

// Valid reports whether r is omitted (inherit) or one of the host-level
// values this release accepts.
func (r SSHRecording) Valid() bool {
	switch r {
	case "", SSHRecordingOff, SSHRecordingTerminalOutput:
		return true
	default:
		return false
	}
}

// generatedHostVars are host vars Generate writes itself; a same-named key
// in a host's passthrough Extra bag would be emitted twice.
var generatedHostVars = []string{"pilot_ssh_recording", "pilot_annotations"}

// lintSSHRecording returns h's ssh_recording and generated-key-collision
// lint issues.
func lintSSHRecording(h Host) []Issue {
	var issues []Issue
	switch {
	case h.SSHRecording == sshRecordingTerminalIOReserved:
		issues = append(issues, Issue{h.Name, "error", `ssh_recording "terminal_io" is reserved for a future release (typed input cannot yet be redacted reliably); use terminal_output or off`})
	case !h.SSHRecording.Valid():
		issues = append(issues, Issue{h.Name, "error", fmt.Sprintf("unknown ssh_recording %q (must be off|terminal_output, or omitted; quote the value if YAML parsed it as a boolean or number)", h.SSHRecording)})
	}
	for _, k := range generatedHostVars {
		if _, ok := h.Extra[k]; ok {
			issues = append(issues, Issue{h.Name, "error", fmt.Sprintf("host var %q is generated by pilot and must not be set directly (use ssh_recording or annotations instead)", k)})
		}
	}
	return issues
}
